/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {forwardRef, useEffect, useRef} from 'react';
import {Plane, useGLTF, useScroll} from '@react-three/drei';
import {useFrame} from '@react-three/fiber';
import {landingPageConfig, showcaseConfig, state} from './state.js';
import {useSnapshot} from 'valtio';
import gsap from "gsap";
export const Pyramid = forwardRef(({children}, ref) => {
  const {nodes, materials} = useGLTF('/pyramid-rounded2.glb');

  const meshRef = useRef();

  const scroll = useScroll();



  const snapshot = useSnapshot(state)



  return (
    <group ref={ref} dispose={null}>
      <mesh ref={meshRef}
            castShadow
            receiveShadow
            geometry={nodes.Cone.geometry}
      >
        {children}
      </mesh>


    </group>
  );
})

useGLTF.preload('/pyramid-rounded2.glb');
