/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useRef} from 'react';
import {Plane, useGLTF} from '@react-three/drei';
import {useFrame} from '@react-three/fiber';
import {landingPageConfig, showcaseConfig, state} from './state.js';
import {useSnapshot} from 'valtio';

export function Pyramid(props) {
  const {nodes, materials} = useGLTF('/pyramid-rounded2.glb');

  const meshRef = useRef();


  useFrame((state, delta) => {
    meshRef.current.rotation.y += delta * 0.5;
    meshRef.current.rotation.x += delta * 0.1;
  })
  const snapshot = useSnapshot(state)



  return (
    <group {...props} dispose={null}>
      <mesh ref={meshRef}
            castShadow
            receiveShadow
            geometry={nodes.Cone.geometry}
      >
        {props.children}
      </mesh>


    </group>
  );
}

useGLTF.preload('/pyramid-rounded2.glb');
